#!/bin/bash


##
#  lighthhtp since runs on another user wont start normal
# 
##
sleep 3

service lighttpd stop
chown -R chip:chip /var/run/lighttpd
chown -R chip:chip /var/cache/lighttpd
chown -R chip:chip /var/log/lighttpd/*
service lighttpd start

#
# start hostapd as long does not start as a service 
#
ifconfig wlan1 up
/usr/sbin/hostapd /etc/hostapd/hostapd.conf &

function halt()
{
	#
	# turn off on halt file in /tmp
	#
	while [[ 1 ]];do
		sleep 2
		kill -9 $(pidof liveimage)
		kill -9 $(pidof demo.sh)
		[[ -f /tmp/halt ]] && telinit 0
	done
}

